### ISSUE TITLE
Broken icon when installing from the Chrome web store.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [developing-today/MastodonFriendCheck#1]
![image](https://user-images.githubusercontent.com/13170204/66268951-e50f9500-e842-11e9-8d14-3c2f2c4128b0.png)
Incorrect package, Details: ¨Impossible to charge the extension icon ¨icon128.png¨.¨.

**Comment by dezren39** [comment]
Thanks for this message from forever ago. Very sorry it broke for unix-like systems. Although it took me.. a while.... I'll get it fixed.
